In [2]:
import numpy as np

arr = np.arange(36).reshape(3,2,6)

print(arr)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [4]:
print(np.random.seed(44))

None


In [17]:
import random

np.random.choice(5, 3, replace=False, p=[0, 0.1, 0.3, 0.6, 0])

array([1, 3, 2])

In [23]:
x = np.array([(1, 2)], dtype=[('a', np.int8), ('b', np.int8)])
x

array([(1, 2)], dtype=[('a', 'i1'), ('b', 'i1')])

In [19]:
np.random.randint(0, 2, size=25, dtype=np.uint8)

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0], dtype=uint8)

In [24]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i4')])

In [26]:
y = np.array([(1,2)],dtype=[('a','<i4'),('b','<i4')]) 
y['a']

array([1])

In [32]:
T = True
F = False

x = [T,F,T,T,T,F,F]
print(f"{x[:-1]}")
print(f"{x[1:]}")

[True, False, True, True, True, False]
[False, True, True, True, False, False]


In [33]:
myarr = np.array([1., 0., np.nan, 3.])
myarr

array([ 1.,  0., nan,  3.])

In [35]:
myarr = np.array([1., 0., np.inf, 3.])
myarr

array([ 1.,  0., inf,  3.])

In [36]:
arr = np.array([[1, 2, 3],
                 [10, 20, 30]])
arr.sum(axis=0)


array([11, 22, 33])

In [37]:
arr.sum(axis=1)

array([ 6, 60])

In [38]:
import numpy as np
 
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print("initial_array : ", str(ini_array));
 
# Array to be added as column
column_to_be_added = np.array([1, 2, 3])
 
# Adding column to numpy array
result = np.hstack((ini_array, np.atleast_2d(column_to_be_added).T))
 
# printing result
print ("resultant array", str(result))

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [42]:
import numpy as np
 
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print("initial_array : ", (ini_array));
 
# Array to be added as column
column_to_be_added = np.array([1, 2, 3])
 
# Adding column to numpy array
result = np.hstack((ini_array, np.atleast_2d(column_to_be_added).T))
 
# printing result
print ("resultant array", (result))

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [45]:
np.empty([2, 2])

array([[0., 0.],
       [0., 0.]])

In [46]:
np.empty([2, 2], dtype=int)

array([[         0, 1072693248],
       [         0, 1074266112]])

In [1]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])

a.reshape(3,2)
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
np.zeros((2, 1),dtype=int)

array([[0],
       [0]])

In [3]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])